### ISSUE TITLE
Exports can't transition scenes

### ISSUE THREAD

**Issue by VoxelTek** [VoxelTek/PaperLily#3]
### Issue
Exports of the game will not transition scenes. This prevents starting a new game and moving to different areas in a loaded game.

### Steps to reproduce
Export the project, try to start a new game. You will be stuck on a loading screen.

Alternatively, load an existing game, and try to navigate backwards or forwards, to another "level" or "room".

### Additional info
No error or log output is given when this occurs. This makes debugging extremely challenging.

**Comment by ButterflyEffect-07** [comment]
`PaperLily-main 2/script/Core/ScreenManager.cs(308,25): Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.`

This might have something to do with it

**Comment by VoxelTek** [comment]
The function `Execute` in `StoryPlayerMoveCommand.cs` (line 42) isn't getting run in the exported build. This means that the game won't transition.

**Comment by VoxelTek** [comment]
Note on this: in exported builds, trying to start a new game will only get to the `PlayEvent` function in `EventManager.cs`, where it should be continuing on into the `Play` function in `StoryPlayer.cs`.

**Comment by VoxelTek** [comment]
The `GetEvent` function in `EventManager.cs` is returning `null`, which causes the game to be unable to progress further.

**Comment by VoxelTek** [comment]
Discovery: at some point, `this.curEvents` in `EventManager.cs` is being set to `null`, probably on initialisation or something, and because of that, a new game won't start. The function `ClearMappings()` in the same script should be setting it to `this.CreateEventBundle()`, but it never actually runs the function `ClearMappings`.

**Comment by VoxelTek** [comment]
Fixed, `.lsb` and `.lsf` files were not getting exported with the game. Adding them fixed both scene transitions and interaction.
